name: Deploy Model to Hugging Face and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python model.py

      - name: Push to Hugging Face Hub
        uses: huggingface/hub-action@main
        with:
          commit_message: "Automated model deployment"
          local_dir: "."
          local_dir_use_symlinks: false
          repo_id: "${{ secrets.HF_USERNAME }}/${{ github.event.repository.name }}"
          repo_type: "model"
          token: "${{ secrets.HF_TOKEN }}"

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Déploiement réussi sur Hugging Face: ${{ github.repository }}'
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: GitHub Actions <actions@github.com>
          body: |
            Le modèle a été déployé avec succès sur le Hub Hugging Face.
            Commit: ${{ github.sha }}
            Repo: https://huggingface.co/${{ secrets.HF_USERNAME }}/${{ github.event.repository.name }}
